services:
    db:
        image: postgres:latest
        env_file: .env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - db_network

volumes:
    pgdata:

networks:
    db_network:
        driver: bridge
